//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public bill()
        {
            this.payments = new HashSet<payment>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> create_date_at { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> order_id { get; set; }
    
        public virtual order order { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
