//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public discount()
        {
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string discount_name { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> create_date_at { get; set; }
        public Nullable<System.DateTime> end_date_at { get; set; }
        public Nullable<int> stock { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
    }
}
