//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string material_name { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
