//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JewelleryShopEntities : DbContext
    {
        public JewelleryShopEntities()
            : base("name=JewelleryShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bill> bills { get; set; }
        public DbSet<cart> carts { get; set; }
        public DbSet<category_product> category_product { get; set; }
        public DbSet<discount> discounts { get; set; }
        public DbSet<gemstone_type> gemstone_type { get; set; }
        public DbSet<material> materials { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<order> orders { get; set; }
        public DbSet<payment> payments { get; set; }
        public DbSet<product_size> product_size { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<size> sizes { get; set; }
        public DbSet<user> users { get; set; }
    }
}
