//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.bills = new HashSet<bill>();
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int id { get; set; }
        public Nullable<int> stock { get; set; }
        public string shipping_address { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_note { get; set; }
        public Nullable<int> discount_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ICollection<bill> bills { get; set; }
        public virtual discount discount { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual user user { get; set; }
    }
}
