//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.carts = new HashSet<cart>();
            this.order_detail = new HashSet<order_detail>();
            this.product_size = new HashSet<product_size>();
        }
    
        public int id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<decimal> price { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<int> product_size_id { get; set; }
        public Nullable<int> material_id { get; set; }
        public Nullable<int> gemstone_type_id { get; set; }
        public Nullable<int> category_id { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
        public virtual category_product category_product { get; set; }
        public virtual gemstone_type gemstone_type { get; set; }
        public virtual material material { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual ICollection<product_size> product_size { get; set; }
    }
}
