//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public size()
        {
            this.product_size = new HashSet<product_size>();
        }
    
        public int id { get; set; }
        public string size_number { get; set; }
    
        public virtual ICollection<product_size> product_size { get; set; }
    }
}
