//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.carts = new HashSet<cart>();
            this.orders = new HashSet<order>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<System.DateTime> create_day_at { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> role_id { get; set; }
    
        public virtual ICollection<cart> carts { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual role role { get; set; }
    }
}
